UPDATE  departamentos SET nombre='Bogotá D.C.' WHERE id_departamento = 1;
UPDATE  departamentos SET nombre='Amazonas' WHERE id_departamento = 2;
UPDATE  departamentos SET nombre='Antioquia' WHERE id_departamento = 3;
UPDATE  departamentos SET nombre='Arauca' WHERE id_departamento = 4;
UPDATE  departamentos SET nombre='Atlántico' WHERE id_departamento = 5;
UPDATE  departamentos SET nombre='Bolívar' WHERE id_departamento = 6;
UPDATE  departamentos SET nombre='Boyacá' WHERE id_departamento = 7;
UPDATE  departamentos SET nombre='Caldas' WHERE id_departamento = 8;
UPDATE  departamentos SET nombre='Caquetá' WHERE id_departamento = 9;
UPDATE  departamentos SET nombre='Casanare' WHERE id_departamento = 10;
UPDATE  departamentos SET nombre='Cauca' WHERE id_departamento = 11;
UPDATE  departamentos SET nombre='Cesar' WHERE id_departamento = 12;
UPDATE  departamentos SET nombre='Chocó' WHERE id_departamento = 13;
UPDATE  departamentos SET nombre='Córdoba' WHERE id_departamento = 14;
UPDATE  departamentos SET nombre='Cundinamarca' WHERE id_departamento = 15;
UPDATE  departamentos SET nombre='Guainía' WHERE id_departamento = 16;
UPDATE  departamentos SET nombre='Guaviare' WHERE id_departamento = 17;
UPDATE  departamentos SET nombre='Huila' WHERE id_departamento = 18;
UPDATE  departamentos SET nombre='La Guajira' WHERE id_departamento = 19;
UPDATE  departamentos SET nombre='Magdalena' WHERE id_departamento = 20;
UPDATE  departamentos SET nombre='Meta' WHERE id_departamento = 21;
UPDATE  departamentos SET nombre='Nariño' WHERE id_departamento = 22;
UPDATE  departamentos SET nombre='Norte de Santander' WHERE id_departamento = 23;
UPDATE  departamentos SET nombre='Putumayo' WHERE id_departamento = 24;
UPDATE  departamentos SET nombre='Quindío' WHERE id_departamento = 25;
UPDATE  departamentos SET nombre='Risaralda' WHERE id_departamento = 26;
UPDATE  departamentos SET nombre='San Andrés y Providencia' WHERE id_departamento = 27;
UPDATE  departamentos SET nombre='Santander' WHERE id_departamento = 28;
UPDATE  departamentos SET nombre='Sucre' WHERE id_departamento = 29;
UPDATE  departamentos SET nombre='Tolima' WHERE id_departamento = 30;
UPDATE  departamentos SET nombre='Valle del Cauca' WHERE id_departamento = 31;
UPDATE  departamentos SET nombre='Vaupés' WHERE id_departamento = 32;
UPDATE  departamentos SET nombre='Vichada' WHERE id_departamento = 33;
UPDATE  ciudad SET municipio='Ebéjico' WHERE id_ciudad = 53;
UPDATE  ciudad SET municipio='Guatapé' WHERE id_ciudad = 69;
UPDATE  ciudad SET municipio='San Andrés de Cuerquia' WHERE id_ciudad = 100;
UPDATE  ciudad SET municipio='San José de la Montaí±a' WHERE id_ciudad = 104;
UPDATE  ciudad SET municipio='Magangué' WHERE id_ciudad = 183;
UPDATE  ciudad SET municipio='Belén' WHERE id_ciudad = 217;
UPDATE  ciudad SET municipio='Betéitiva' WHERE id_ciudad = 219;
UPDATE  ciudad SET municipio='Ciénega' WHERE id_ciudad = 236;
UPDATE  ciudad SET municipio='San José de Pare' WHERE id_ciudad = 294;
UPDATE  ciudad SET municipio='Turmequé' WHERE id_ciudad = 328;
UPDATE  ciudad SET municipio='San José' WHERE id_ciudad = 358;
UPDATE  ciudad SET municipio='Belén de los Andaquíes' WHERE id_ciudad = 365;
UPDATE  ciudad SET municipio='San José del Fragua' WHERE id_ciudad = 374;
UPDATE  ciudad SET municipio='Orocué' WHERE id_ciudad = 387;
UPDATE  ciudad SET municipio='Orocué' WHERE id_ciudad = 406;
UPDATE  ciudad SET municipio='Guachené' WHERE id_ciudad = 429;
UPDATE  ciudad SET municipio='Puracé - Coconuco' WHERE id_ciudad = 445;
UPDATE  ciudad SET municipio='Cértegui' WHERE id_ciudad = 492;
UPDATE  ciudad SET municipio='El Carmen del Darién' WHERE id_ciudad = 496;
UPDATE  ciudad SET municipio='San José del Palmar' WHERE id_ciudad = 509;
UPDATE  ciudad SET municipio='Cereté' WHERE id_ciudad = 518;
UPDATE  ciudad SET municipio='Ciénaga de Oro' WHERE id_ciudad = 521;
UPDATE  ciudad SET municipio='San Andrés de Sotavento' WHERE id_ciudad = 534;
UPDATE  ciudad SET municipio='San José de Uré' WHERE id_ciudad = 538;
UPDATE  ciudad SET municipio='Gutiérrez' WHERE id_ciudad = 589;
UPDATE  ciudad SET municipio='Jerusalén' WHERE id_ciudad = 590;
UPDATE  ciudad SET municipio='Sesquilé' WHERE id_ciudad = 625;
UPDATE  ciudad SET municipio='Sibaté' WHERE id_ciudad = 626;
UPDATE  ciudad SET municipio='Ubaté' WHERE id_ciudad = 647;
UPDATE  ciudad SET municipio='San José del Guaviare' WHERE id_ciudad = 668;
UPDATE  ciudad SET municipio='Ciénaga' WHERE id_ciudad = 730;
UPDATE  ciudad SET municipio='El Retén' WHERE id_ciudad = 734;
UPDATE  ciudad SET municipio='Belén' WHERE id_ciudad = 789;
UPDATE  ciudad SET municipio='Imués' WHERE id_ciudad = 810;
UPDATE  ciudad SET municipio='La Playa de Belén' WHERE id_ciudad = 866;
UPDATE  ciudad SET municipio='Génova' WHERE id_ciudad = 906;
UPDATE  ciudad SET municipio='Belén de Umbré' WHERE id_ciudad = 915;
UPDATE  ciudad SET municipio='San Andrés' WHERE id_ciudad = 996;
UPDATE  ciudad SET municipio='San José de Miranda' WHERE id_ciudad = 1000;
UPDATE  ciudad SET municipio='Valle de San José' WHERE id_ciudad = 1011;
UPDATE  ciudad SET municipio='Vélez' WHERE id_ciudad = 1012;
UPDATE  ciudad SET municipio='Sampués' WHERE id_ciudad = 1032;
UPDATE  ciudad SET municipio='Sincé' WHERE id_ciudad = 1039;
UPDATE  ciudad SET municipio='Ibagué' WHERE id_ciudad = 1042;
UPDATE  ciudad SET municipio='Lérida' WHERE id_ciudad = 1065;
UPDATE  ciudad SET municipio='Calima - El Darién' WHERE id_ciudad = 1099;
UPDATE  ciudad SET municipio='Yavaraté' WHERE id_ciudad = 1136;
UPDATE  ciudad SET municipio='Angelópolis' WHERE id_ciudad = 19;
UPDATE  ciudad SET municipio='Apartadó' WHERE id_ciudad = 23;
UPDATE  ciudad SET municipio='Chigorodó' WHERE id_ciudad = 44;
UPDATE  ciudad SET municipio='Concepción' WHERE id_ciudad = 48;
UPDATE  ciudad SET municipio='Gómez Plata' WHERE id_ciudad = 65;
UPDATE  ciudad SET municipio='Jericó' WHERE id_ciudad = 75;
UPDATE  ciudad SET municipio='La Unión' WHERE id_ciudad = 79;
UPDATE  ciudad SET municipio='Murindó' WHERE id_ciudad = 84;
UPDATE  ciudad SET municipio='San Jerónimo' WHERE id_ciudad = 103;
UPDATE  ciudad SET municipio='Sonsón' WHERE id_ciudad = 117;
UPDATE  ciudad SET municipio='Yolombó' WHERE id_ciudad = 134;
UPDATE  ciudad SET municipio='Yondó' WHERE id_ciudad = 135;
UPDATE  ciudad SET municipio='Puerto Rondón' WHERE id_ciudad = 141;
UPDATE  ciudad SET municipio='Piojó' WHERE id_ciudad = 154;
UPDATE  ciudad SET municipio='Repelón' WHERE id_ciudad = 158;
UPDATE  ciudad SET municipio='Córdoba' WHERE id_ciudad = 178;
UPDATE  ciudad SET municipio='El Peí±ón' WHERE id_ciudad = 181;
UPDATE  ciudad SET municipio='San Cristóbal' WHERE id_ciudad = 193;
UPDATE  ciudad SET municipio='Cómbita' WHERE id_ciudad = 237;
UPDATE  ciudad SET municipio='Jericó' WHERE id_ciudad = 258;
UPDATE  ciudad SET municipio='Nuevo Colón' WHERE id_ciudad = 272;
UPDATE  ciudad SET municipio='Rondón' WHERE id_ciudad = 289;
UPDATE  ciudad SET municipio='Susacón' WHERE id_ciudad = 314;
UPDATE  ciudad SET municipio='Tópaga' WHERE id_ciudad = 325;
UPDATE  ciudad SET municipio='Jambaló' WHERE id_ciudad = 432;
UPDATE  ciudad SET municipio='López de Micay' WHERE id_ciudad = 435;
UPDATE  ciudad SET municipio='Piendamó' WHERE id_ciudad = 443;
UPDATE  ciudad SET municipio='Totoró' WHERE id_ciudad = 457;
UPDATE  ciudad SET municipio='Manaure Balcón del Cesar' WHERE id_ciudad = 475;
UPDATE  ciudad SET municipio='Quibdó' WHERE id_ciudad = 484;
UPDATE  ciudad SET municipio='Alto Baudó' WHERE id_ciudad = 486;
UPDATE  ciudad SET municipio='Bagadó' WHERE id_ciudad = 488;
UPDATE  ciudad SET municipio='Bajo Baudó' WHERE id_ciudad = 490;
UPDATE  ciudad SET municipio='El Cantón de San Pablo' WHERE id_ciudad = 494;
UPDATE  ciudad SET municipio='Juradó' WHERE id_ciudad = 499;
UPDATE  ciudad SET municipio='Lloró' WHERE id_ciudad = 500;
UPDATE  ciudad SET municipio='Medio Baudó' WHERE id_ciudad = 502;
UPDATE  ciudad SET municipio='Nóvita' WHERE id_ciudad = 504;
UPDATE  ciudad SET municipio='Río Iró' WHERE id_ciudad = 506;
UPDATE  ciudad SET municipio='Tadó' WHERE id_ciudad = 511;
UPDATE  ciudad SET municipio='Unión Panamericana' WHERE id_ciudad = 513;
UPDATE  ciudad SET municipio='Los Córdobas' WHERE id_ciudad = 524;
UPDATE  ciudad SET municipio='El Peí±ón' WHERE id_ciudad = 568;
UPDATE  ciudad SET municipio='Fómeque' WHERE id_ciudad = 571;
UPDATE  ciudad SET municipio='Nemocón' WHERE id_ciudad = 604;
UPDATE  ciudad SET municipio='Sopó' WHERE id_ciudad = 630;
UPDATE  ciudad SET municipio='Villagómez' WHERE id_ciudad = 653;
UPDATE  ciudad SET municipio='Villapinzón' WHERE id_ciudad = 654;
UPDATE  ciudad SET municipio='Zipacón' WHERE id_ciudad = 658;
UPDATE  ciudad SET municipio='Garzón' WHERE id_ciudad = 682;
UPDATE  ciudad SET municipio='Distracción' WHERE id_ciudad = 713;
UPDATE  ciudad SET municipio='El Pií±ón' WHERE id_ciudad = 733;
UPDATE  ciudad SET municipio='Fundación' WHERE id_ciudad = 735;
UPDATE  ciudad SET municipio='San Zenón' WHERE id_ciudad = 747;
UPDATE  ciudad SET municipio='Puerto López' WHERE id_ciudad = 775;
UPDATE  ciudad SET municipio='Colón' WHERE id_ciudad = 792;
UPDATE  ciudad SET municipio='Córdoba' WHERE id_ciudad = 795;
UPDATE  ciudad SET municipio='El Tablón de Gómez' WHERE id_ciudad = 802;
UPDATE  ciudad SET municipio='La Unión' WHERE id_ciudad = 816;
UPDATE  ciudad SET municipio='Convención' WHERE id_ciudad = 856;
UPDATE  ciudad SET municipio='Colón' WHERE id_ciudad = 888;
UPDATE  ciudad SET municipio='Villagarzón' WHERE id_ciudad = 899;
UPDATE  ciudad SET municipio='Córdoba' WHERE id_ciudad = 904;
UPDATE  ciudad SET municipio='Mistrató' WHERE id_ciudad = 921;
UPDATE  ciudad SET municipio='Concepción' WHERE id_ciudad = 949;
UPDATE  ciudad SET municipio='Contratación' WHERE id_ciudad = 951;
UPDATE  ciudad SET municipio='El Peí±ón' WHERE id_ciudad = 956;
UPDATE  ciudad SET municipio='El Playón' WHERE id_ciudad = 957;
UPDATE  ciudad SET municipio='Girón' WHERE id_ciudad = 964;
UPDATE  ciudad SET municipio='Santa Helena del Opón' WHERE id_ciudad = 1004;
UPDATE  ciudad SET municipio='Colosó' WHERE id_ciudad = 1020;
UPDATE  ciudad SET municipio='La Unión' WHERE id_ciudad = 1026;
UPDATE  ciudad SET municipio='Purificación' WHERE id_ciudad = 1075;
UPDATE  ciudad SET municipio='La Unión' WHERE id_ciudad = 1112;
UPDATE  ciudad SET municipio='Mirití-Paraná' WHERE id_ciudad = 6;
UPDATE  ciudad SET municipio='Medellín' WHERE id_ciudad = 12;
UPDATE  ciudad SET municipio='Abriaquí' WHERE id_ciudad = 14;
UPDATE  ciudad SET municipio='Anorí' WHERE id_ciudad = 21;
UPDATE  ciudad SET municipio='Caracolí' WHERE id_ciudad = 39;
UPDATE  ciudad SET municipio='Carolina del Príncipe' WHERE id_ciudad = 42;
UPDATE  ciudad SET municipio='Ciudad Bolívar' WHERE id_ciudad = 46;
UPDATE  ciudad SET municipio='Entrerríos' WHERE id_ciudad = 59;
UPDATE  ciudad SET municipio='Itagí¼í' WHERE id_ciudad = 72;
UPDATE  ciudad SET municipio='Jardín' WHERE id_ciudad = 74;
UPDATE  ciudad SET municipio='Nechí' WHERE id_ciudad = 87;
UPDATE  ciudad SET municipio='Necoclí' WHERE id_ciudad = 88;
UPDATE  ciudad SET municipio='Puerto Berrío' WHERE id_ciudad = 92;
UPDATE  ciudad SET municipio='Titiribí' WHERE id_ciudad = 122;
UPDATE  ciudad SET municipio='Valparaíso' WHERE id_ciudad = 128;
UPDATE  ciudad SET municipio='Vegachí' WHERE id_ciudad = 129;
UPDATE  ciudad SET municipio='Yalí' WHERE id_ciudad = 132;
UPDATE  ciudad SET municipio='Manatí' WHERE id_ciudad = 152;
UPDATE  ciudad SET municipio='Usiacurí' WHERE id_ciudad = 166;
UPDATE  ciudad SET municipio='Achí' WHERE id_ciudad = 168;
UPDATE  ciudad SET municipio='El Carmen de Bolívar' WHERE id_ciudad = 179;
UPDATE  ciudad SET municipio='Norosí' WHERE id_ciudad = 189;
UPDATE  ciudad SET municipio='Río Viejo' WHERE id_ciudad = 192;
UPDATE  ciudad SET municipio='San Martín de Loba' WHERE id_ciudad = 199;
UPDATE  ciudad SET municipio='Simití' WHERE id_ciudad = 205;
UPDATE  ciudad SET municipio='Chíquiza' WHERE id_ciudad = 230;
UPDATE  ciudad SET municipio='Cuítiva' WHERE id_ciudad = 243;
UPDATE  ciudad SET municipio='Maripí' WHERE id_ciudad = 264;
UPDATE  ciudad SET municipio='Monguí' WHERE id_ciudad = 267;
UPDATE  ciudad SET municipio='Paz de Río' WHERE id_ciudad = 282;
UPDATE  ciudad SET municipio='Quípama' WHERE id_ciudad = 286;
UPDATE  ciudad SET municipio='Ramiriquí' WHERE id_ciudad = 287;
UPDATE  ciudad SET municipio='Togí¼í' WHERE id_ciudad = 324;
UPDATE  ciudad SET municipio='Belí©n de los Andaquíes' WHERE id_ciudad = 365;
UPDATE  ciudad SET municipio='Valparaíso' WHERE id_ciudad = 378;
UPDATE  ciudad SET municipio='Maní' WHERE id_ciudad = 384;
UPDATE  ciudad SET municipio='Maní' WHERE id_ciudad = 403;
UPDATE  ciudad SET municipio='Bolívar' WHERE id_ciudad = 421;
UPDATE  ciudad SET municipio='Cajibío' WHERE id_ciudad = 423;
UPDATE  ciudad SET municipio='Timbío' WHERE id_ciudad = 454;
UPDATE  ciudad SET municipio='Timbiquí' WHERE id_ciudad = 455;
UPDATE  ciudad SET municipio='Toribío' WHERE id_ciudad = 456;
UPDATE  ciudad SET municipio='Agustín Codazzi' WHERE id_ciudad = 461;
UPDATE  ciudad SET municipio='Curumaní' WHERE id_ciudad = 467;
UPDATE  ciudad SET municipio='Río de Oro' WHERE id_ciudad = 479;
UPDATE  ciudad SET municipio='San Martín' WHERE id_ciudad = 482;
UPDATE  ciudad SET municipio='Acandí' WHERE id_ciudad = 485;
UPDATE  ciudad SET municipio='Nuquí' WHERE id_ciudad = 505;
UPDATE  ciudad SET municipio='Río Irí³' WHERE id_ciudad = 506;
UPDATE  ciudad SET municipio='Río Quito' WHERE id_ciudad = 507;
UPDATE  ciudad SET municipio='Sipí' WHERE id_ciudad = 510;
UPDATE  ciudad SET municipio='Montelíbano' WHERE id_ciudad = 526;
UPDATE  ciudad SET municipio='Purísima' WHERE id_ciudad = 532;
UPDATE  ciudad SET municipio='Tuchín' WHERE id_ciudad = 542;
UPDATE  ciudad SET municipio='Caparrapí' WHERE id_ciudad = 556;
UPDATE  ciudad SET municipio='Chaguaní' WHERE id_ciudad = 559;
UPDATE  ciudad SET municipio='Choachí' WHERE id_ciudad = 562;
UPDATE  ciudad SET municipio='Guataquí' WHERE id_ciudad = 585;
UPDATE  ciudad SET municipio='Guayabal de Síquima' WHERE id_ciudad = 587;
UPDATE  ciudad SET municipio='Junín' WHERE id_ciudad = 591;
UPDATE  ciudad SET municipio='Pulí' WHERE id_ciudad = 614;
UPDATE  ciudad SET municipio='Topaipí' WHERE id_ciudad = 644;
UPDATE  ciudad SET municipio='Vianí' WHERE id_ciudad = 652;
UPDATE  ciudad SET municipio='Yacopí' WHERE id_ciudad = 657;
UPDATE  ciudad SET municipio='Inírida' WHERE id_ciudad = 660;
UPDATE  ciudad SET municipio='íquira' WHERE id_ciudad = 686;
UPDATE  ciudad SET municipio='San Agustín' WHERE id_ciudad = 699;
UPDATE  ciudad SET municipio='Ariguaní' WHERE id_ciudad = 727;
UPDATE  ciudad SET municipio='Sabanas de San íngel' WHERE id_ciudad = 744;
UPDATE  ciudad SET municipio='San Martín' WHERE id_ciudad = 781;
UPDATE  ciudad SET municipio='Chachagí¼í' WHERE id_ciudad = 791;
UPDATE  ciudad SET municipio='Magí¼í Payán' WHERE id_ciudad = 820;
UPDATE  ciudad SET municipio='Potosí' WHERE id_ciudad = 827;
UPDATE  ciudad SET municipio='íbrego' WHERE id_ciudad = 848;
UPDATE  ciudad SET municipio='Hacarí' WHERE id_ciudad = 863;
UPDATE  ciudad SET municipio='Puerto Asís' WHERE id_ciudad = 890;
UPDATE  ciudad SET municipio='Puerto Leguízamo' WHERE id_ciudad = 893;
UPDATE  ciudad SET municipio='Bolívar' WHERE id_ciudad = 937;
UPDATE  ciudad SET municipio='Carcasí' WHERE id_ciudad = 941;
UPDATE  ciudad SET municipio='Curití' WHERE id_ciudad = 953;
UPDATE  ciudad SET municipio='El Carmen de Chucurí' WHERE id_ciudad = 954;
UPDATE  ciudad SET municipio='San Joaquín' WHERE id_ciudad = 999;
UPDATE  ciudad SET municipio='San Vicente de Chucurí' WHERE id_ciudad = 1002;
UPDATE  ciudad SET municipio='Líbano' WHERE id_ciudad = 1066;
UPDATE  ciudad SET municipio='Bolívar' WHERE id_ciudad = 1094;
UPDATE  ciudad SET municipio='El íguila' WHERE id_ciudad = 1103;
UPDATE  ciudad SET municipio='Guacarí' WHERE id_ciudad = 1109;
UPDATE  ciudad SET municipio='Jamundí' WHERE id_ciudad = 1110;
UPDATE  ciudad SET municipio='Riofrío' WHERE id_ciudad = 1118;
UPDATE  ciudad SET municipio='Puerto Nariño' WHERE id_ciudad = 9;
UPDATE  ciudad SET municipio='Briceño' WHERE id_ciudad = 32;
UPDATE  ciudad SET municipio='Cañasgordas' WHERE id_ciudad = 38;
UPDATE  ciudad SET municipio='El Peñol' WHERE id_ciudad = 56;
UPDATE  ciudad SET municipio='Nariño' WHERE id_ciudad = 86;
UPDATE  ciudad SET municipio='San José de la Montaña' WHERE id_ciudad = 104;
UPDATE  ciudad SET municipio='El Peñón' WHERE id_ciudad = 181;
UPDATE  ciudad SET municipio='Briceño' WHERE id_ciudad = 222;
UPDATE  ciudad SET municipio='La Montañita' WHERE id_ciudad = 370;
UPDATE  ciudad SET municipio='Moñitos' WHERE id_ciudad = 527;
UPDATE  ciudad SET municipio='El Peñón' WHERE id_ciudad = 568;
UPDATE  ciudad SET municipio='La Peña' WHERE id_ciudad = 595;
UPDATE  ciudad SET municipio='Nariño' WHERE id_ciudad = 603;
UPDATE  ciudad SET municipio='El Piñón' WHERE id_ciudad = 733;
UPDATE  ciudad SET municipio='Pijiño del Carmen' WHERE id_ciudad = 739;
UPDATE  ciudad SET municipio='El Peñol' WHERE id_ciudad = 800;
UPDATE  ciudad SET municipio='Nariño' WHERE id_ciudad = 823;
UPDATE  ciudad SET municipio='Ocaña' WHERE id_ciudad = 871;
UPDATE  ciudad SET municipio='El Peñón' WHERE id_ciudad = 956;
UPDATE  ciudad SET municipio='Coveñas' WHERE id_ciudad = 1022;
UPDATE  ciudad SET municipio='Saldaña' WHERE id_ciudad = 1079;
UPDATE  ciudad SET municipio='Puerto Carreño' WHERE id_ciudad = 1137;
UPDATE  ciudad SET municipio='Itagúí' WHERE id_ciudad = 72;
UPDATE  ciudad SET municipio='Gúicán' WHERE id_ciudad = 255;
UPDATE  ciudad SET municipio='Togúí' WHERE id_ciudad = 324;
UPDATE  ciudad SET municipio='Chachagúí' WHERE id_ciudad = 791;
UPDATE  ciudad SET municipio='Magúí Payán' WHERE id_ciudad = 820;
UPDATE  ciudad SET municipio='Gúepsa' WHERE id_ciudad = 969;
UPDATE  ciudad SET municipio='Río Iró' WHERE id_ciudad = 506;
UPDATE  ciudad SET municipio='Concepción' WHERE id_ciudad = 48;
UPDATE  ciudad SET municipio='El Santuario' WHERE id_ciudad = 58;
UPDATE  ciudad SET municipio='Entrerríos' WHERE id_ciudad = 59;
UPDATE  ciudad SET municipio='La Unión' WHERE id_ciudad = 79;
UPDATE  ciudad SET municipio='Puerto Berrío' WHERE id_ciudad = 92;
UPDATE  ciudad SET municipio='Remedios' WHERE id_ciudad = 95;
UPDATE  ciudad SET municipio='Rionegro' WHERE id_ciudad = 96;
UPDATE  ciudad SET municipio='Santa Fe de Antioquia' WHERE id_ciudad = 113;
UPDATE  ciudad SET municipio='Piojó' WHERE id_ciudad = 154;
UPDATE  ciudad SET municipio='Altos del Rosario' WHERE id_ciudad = 169;
UPDATE  ciudad SET municipio='Río Viejo' WHERE id_ciudad = 192;
UPDATE  ciudad SET municipio='Tiquisio' WHERE id_ciudad = 208;
UPDATE  ciudad SET municipio='Paz de Río' WHERE id_ciudad = 282;
UPDATE  ciudad SET municipio='Riosucio' WHERE id_ciudad = 355;
UPDATE  ciudad SET municipio='Cajibío' WHERE id_ciudad = 423;
UPDATE  ciudad SET municipio='Timbío' WHERE id_ciudad = 454;
UPDATE  ciudad SET municipio='Toribío' WHERE id_ciudad = 456;
UPDATE  ciudad SET municipio='Río de Oro' WHERE id_ciudad = 479;
UPDATE  ciudad SET municipio='Medio Atrato' WHERE id_ciudad = 501;
UPDATE  ciudad SET municipio='Medio Baudó' WHERE id_ciudad = 502;
UPDATE  ciudad SET municipio='Medio San Juan' WHERE id_ciudad = 503;
UPDATE  ciudad SET municipio='Río Iró' WHERE id_ciudad = 506;
UPDATE  ciudad SET municipio='Río Quito' WHERE id_ciudad = 507;
UPDATE  ciudad SET municipio='Riosucio' WHERE id_ciudad = 508;
UPDATE  ciudad SET municipio='Unión Panamericana' WHERE id_ciudad = 513;
UPDATE  ciudad SET municipio='Chinú' WHERE id_ciudad = 520;
UPDATE  ciudad SET municipio='Sahagún' WHERE id_ciudad = 533;
UPDATE  ciudad SET municipio='Agua de Dios' WHERE id_ciudad = 544;
UPDATE  ciudad SET municipio='El Colegio' WHERE id_ciudad = 567;
UPDATE  ciudad SET municipio='Fúquene' WHERE id_ciudad = 574;
UPDATE  ciudad SET municipio='San Antonio del Tequendama' WHERE id_ciudad = 619;
UPDATE  ciudad SET municipio='San Juan de Rioseco' WHERE id_ciudad = 623;
UPDATE  ciudad SET municipio='Tabio' WHERE id_ciudad = 636;
UPDATE  ciudad SET municipio='Viotá' WHERE id_ciudad = 656;
UPDATE  ciudad SET municipio='Riohacha' WHERE id_ciudad = 709;
UPDATE  ciudad SET municipio='Distracción' WHERE id_ciudad = 713;
UPDATE  ciudad SET municipio='Cerro de San Antonio' WHERE id_ciudad = 728;
UPDATE  ciudad SET municipio='Fundación' WHERE id_ciudad = 735;
UPDATE  ciudad SET municipio='Sitionuevo' WHERE id_ciudad = 750;
UPDATE  ciudad SET municipio='Villavicencio' WHERE id_ciudad = 754;
UPDATE  ciudad SET municipio='El Calvario' WHERE id_ciudad = 761;
UPDATE  ciudad SET municipio='El Rosario' WHERE id_ciudad = 801;
UPDATE  ciudad SET municipio='La Unión' WHERE id_ciudad = 816;
UPDATE  ciudad SET municipio='Túquerres' WHERE id_ciudad = 845;
UPDATE  ciudad SET municipio='Cúcuta' WHERE id_ciudad = 847;
UPDATE  ciudad SET municipio='Convención' WHERE id_ciudad = 856;
UPDATE  ciudad SET municipio='Los Patios' WHERE id_ciudad = 868;
UPDATE  ciudad SET municipio='Tibú' WHERE id_ciudad = 883;
UPDATE  ciudad SET municipio='Villa del Rosario' WHERE id_ciudad = 886;
UPDATE  ciudad SET municipio='Santuario' WHERE id_ciudad = 925;
UPDATE  ciudad SET municipio='Concepción' WHERE id_ciudad = 949;
UPDATE  ciudad SET municipio='Contratación' WHERE id_ciudad = 951;
UPDATE  ciudad SET municipio='Jesús Maré' WHERE id_ciudad = 971;
UPDATE  ciudad SET municipio='Puente Nacional' WHERE id_ciudad = 991;
UPDATE  ciudad SET municipio='Rionegro' WHERE id_ciudad = 994;
UPDATE  ciudad SET municipio='La Unión' WHERE id_ciudad = 1026;
UPDATE  ciudad SET municipio='Santiago de Tolú' WHERE id_ciudad = 1038;
UPDATE  ciudad SET municipio='Purificación' WHERE id_ciudad = 1075;
UPDATE  ciudad SET municipio='Rioblanco' WHERE id_ciudad = 1076;
UPDATE  ciudad SET municipio='San Antonio' WHERE id_ciudad = 1080;
UPDATE  ciudad SET municipio='El Dovio' WHERE id_ciudad = 1106;
UPDATE  ciudad SET municipio='La Unión' WHERE id_ciudad = 1112;
UPDATE  ciudad SET municipio='Riofrío' WHERE id_ciudad = 1118;
UPDATE  ciudad SET municipio='Mitú' WHERE id_ciudad = 1131;
UPDATE  ciudad SET municipio='Carurú' WHERE id_ciudad = 1132;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 167;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 168;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 169;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 170;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 171;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 172;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 173;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 174;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 175;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 176;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 177;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 178;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 179;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 180;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 181;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 182;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 183;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 184;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 185;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 186;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 187;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 188;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 189;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 190;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 191;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 192;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 193;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 194;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 195;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 196;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 197;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 198;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 199;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 200;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 201;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 202;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 203;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 204;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 205;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 206;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 207;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 208;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 209;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 210;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 211;
UPDATE  ciudad SET id_departamento='Bolívar' WHERE id_ciudad = 212;
UPDATE  ciudad SET id_departamento='Quindío' WHERE id_ciudad = 900;
UPDATE  ciudad SET id_departamento='Quindío' WHERE id_ciudad = 901;
UPDATE  ciudad SET id_departamento='Quindío' WHERE id_ciudad = 902;
UPDATE  ciudad SET id_departamento='Quindío' WHERE id_ciudad = 903;
UPDATE  ciudad SET id_departamento='Quindío' WHERE id_ciudad = 904;
UPDATE  ciudad SET id_departamento='Quindío' WHERE id_ciudad = 905;
UPDATE  ciudad SET id_departamento='Quindío' WHERE id_ciudad = 906;
UPDATE  ciudad SET id_departamento='Quindío' WHERE id_ciudad = 907;
UPDATE  ciudad SET id_departamento='Quindío' WHERE id_ciudad = 908;
UPDATE  ciudad SET id_departamento='Quindío' WHERE id_ciudad = 909;
UPDATE  ciudad SET id_departamento='Quindío' WHERE id_ciudad = 910;
UPDATE  ciudad SET id_departamento='Quindío' WHERE id_ciudad = 911;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 484;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 485;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 486;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 487;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 488;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 489;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 490;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 491;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 492;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 493;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 494;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 495;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 496;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 497;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 498;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 499;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 500;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 501;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 502;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 503;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 504;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 505;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 506;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 507;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 508;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 509;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 510;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 511;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 512;
UPDATE  ciudad SET id_departamento='Chocó' WHERE id_ciudad = 513;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 514;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 515;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 516;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 517;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 518;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 519;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 520;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 521;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 522;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 523;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 524;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 525;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 526;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 527;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 528;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 529;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 530;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 531;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 532;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 533;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 534;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 535;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 536;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 537;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 538;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 539;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 540;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 541;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 542;
UPDATE  ciudad SET id_departamento='Córdoba' WHERE id_ciudad = 543;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 784;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 785;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 786;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 787;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 788;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 789;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 790;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 791;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 792;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 793;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 794;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 796;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 797;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 798;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 795;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 799;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 800;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 801;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 802;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 803;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 804;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 805;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 806;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 807;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 808;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 809;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 810;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 811;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 812;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 813;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 814;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 815;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 816;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 817;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 818;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 819;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 820;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 821;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 822;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 823;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 824;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 825;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 783;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 826;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 827;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 828;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 829;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 830;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 831;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 832;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 833;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 834;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 835;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 836;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 837;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 838;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 839;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 840;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 841;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 842;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 843;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 844;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 845;
UPDATE  ciudad SET id_departamento='Nariño' WHERE id_ciudad = 846;




